### ISSUE TITLE
"Unrecognized function or variable 'bioinfochecknargin'." Error While Computing Cluster Maps

### ISSUE THREAD

**Issue by batiyilmaz** [dlopezg/mvpalab#14]
Dear Dr. David López-García,

The toolbox is wonderful, thank you for providing and making it publicly available! 

While producing the time-resolved MVPA for 3 subjects to yield a mean decoding accuracy, I've encountered an issue whilst computing cluster-based permutation statistics of it.

Here's the error prompt for the reference:
"Unrecognized function or variable 'bioinfochecknargin'.

Error in mafdr (line 65)
bioinfochecknargin(nargin,1,mfilename);

Error in mvpalab_computepermtest (line 218)
    fdr = mafdr(hnorm,'bhfdr','true');

Error in mvpalab_permtest (line 54)
    stats = mvpalab_computepermtest(cfg,results,permuted_maps);

Error in mvpalab_permtest (line 43)
            stats.(fname) = mvpalab_permtest(cfg,res,pmap,fname);

Error in analysisController (line 27)
    stats = mvpalab_permtest(cfg,result,permaps);

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in studyView/startAnalysisPushed (line 1225)
                    evalin('base', 'run analysisController');

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 172)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn."

I've been trying to solve this issue to see statistically significant cluster windows, hence timepoints.
Have you ever encountered this issue before and if it's the case, how should I approach resolving it?

Thank you for your time and help in advance.

Best,
Bati

**Comment by batiyilmaz** [comment]
Through my quick investigation, I've found out that this might be related to MATLAB's 'mafdr' function within its Bioinformatics Toolbox, however, I don't have any access to that toolbox. I wanted to kindly ask whether it is possible to compute it without it? Thank you again for your time!

**Comment by dlopezg** [comment]
Thank for reporting this issue. In order to compute the statistical analysis the Bioinformatics Toolbox should be installed. I have added this information to the wiki.
