### ISSUE TITLE
Can this mvpalab be used to analyse more than 2 classified condistions?

### ISSUE THREAD

**Issue by HuYQ115** [dlopezg/mvpalab#7]
Can this mvpalab be used to analyse more than 2 condistions?  Why I have created 4 condition identifiers, but though the GUI, I can only two of them, the first and second one. Also the random probability should be 0.25, but the results calculated by the lab show the random probabality is around 0.5

**Comment by dlopezg** [comment]
Good morning, unfortunately the MVPAlab Toolbox does not support multiclass classification yet. As you mentioned, if you create four condition identifiers the software only uses the first two and compute binary classification, which result in a chance level of 0.5. 

The MVPAlab Toolbox is quite recent and it is in constant development. Multiclass classification and other useful features are planning to be implemented in the future.

**Comment by HuYQ115** [comment]
OK. Wish we can meet those new features soon in the future!Thank you very much!
