### ISSUE TITLE
Working with .set file

### ISSUE THREAD

**Issue by ravidasucl** [dlopezg/mvpalab#9]
Dear David,

I'm attampting to run an analysis on some data that have been epoched with EEGlab but seem to be falling at the first hurdle. The documentation says that MVPALab can take .set files as input, however after pointing to these data in the configuration and setting the analysis paramters, there is an import fail message due to no data files being found?

Are you able to advise on the likely cause of this error? Should I go back into EEGLab and re-save all the .set files as .mat instead? If you would like to reproduce the error, I can send you an example .set file. 

Many thanks,

Ravi

The error is as follows:

Error using mvpalab_import (line 53)
Data files not found. Directory: C:\<filepath>\CS+epoched\

Error in analysisController (line 8)
[cfg,~,fv] = mvpalab_import(cfg);

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in studyView/startAnalysisPushed (line 1223)
                    evalin('base', 'run analysisController');
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 335)
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by dlopezg** [comment]
Hi Ravi, thanks for your message. 

Could you send your .set file to me in order to reproduce the error you are getting? 

David

**Comment by dlopezg** [comment]
Hi Ravi, I have check your files. The problem seems to be not related to MVPAlab Toolbox. When I tried to open your .set files with EEGLAB I got the same error. According to EEGLAB documentation, EEG datasets are usually saved in two files, the metadata file (.set) and the data file (.fdt). If you renamed the .set file, please be sure to rename the .fdt as well. Additionally, .set files and .fdt files should be in the same folder. 


Please

**Comment by ravidasucl** [comment]
Hi David,

Thanks for the response. I'm afraid the corresponding .fdt files were in the same location as the .set files and names corresponded when this error was given. ould you recommend not working with .set files?

All the best,

Ravi
________________________________

**Comment by dlopezg** [comment]
It is easier to work with .mat files since they are directly imported to MVPAlab. Contrary, to import .set files the EEGlab function **pop_loadset** is required. The error you are getting is thrown by this function, so you should not be able  to load your .set files into eeglab.

**Comment by ravidasucl** [comment]
Hi David,

Thanks for that. There are no issues with pop_loadset when loading the set files into EEGlab. We have already done some ERP analyses on these data and there have been no issues with any of the files so far.

All the best,

Ravi
________________________________

**Comment by dlopezg** [comment]
That's weird. Would you mind sharing some .set and .fdt files with me? I am going to try to reproduce the exact same error. Thanks in advance, David.

**Comment by ravidasucl** [comment]
Hi David,

A couple are attached as OneDrive links. Please keep these confidential as they are actual study data.

[https://res-geo.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]subject_006.fdt<https://liveuclac-my.sharepoint.com/:u:/g/personal/ucjtrd0_ucl_ac_uk/ETxR8PKLrFVItFkW2AVs9CkBVkkOeXzP3uvd5wYAjICRlQ>
[https://res-geo.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]subject_006.set<https://liveuclac-my.sharepoint.com/:u:/g/personal/ucjtrd0_ucl_ac_uk/ESpUYKXwd_5AvzETAypZeQsBwB_CEiMZZvUyFmhnstjMpw>
[https://res-geo.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]subject_013.fdt<https://liveuclac-my.sharepoint.com/:u:/g/personal/ucjtrd0_ucl_ac_uk/EUbotriCGrNDgONzDOECQMQBwP11PC6LyoMnkPuwH4atfA>
[https://res-geo.cdn.office.net/assets/mail/file-icon/png/generic_16x16.png]subject_013.set<https://liveuclac-my.sharepoint.com/:u:/g/personal/ucjtrd0_ucl_ac_uk/EeNXFViS8IdIuXpPBUPiBDQBvh0SKWFF3L7pZDllsns3ng>

Many thanks and best wishes,

Ravi
________________________________

**Comment by dlopezg** [comment]
Hi Ravi, I deleted your previous message to keep your data private. These messages are publicly available on GitHub. Please contact me directly at dlopez[at]ugr[dot]com for sharing the data. Thanks, David.
